/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FcIcon {
        "color": string;
        "group": string;
        "name": string;
        "size": string;
    }
    interface FcIllustration {
        "name": string;
        "size": string;
    }
    interface FcImage {
        "height": number;
        "name": string;
        "styles": object;
        "width": number;
    }
}
declare global {
    interface HTMLFcIconElement extends Components.FcIcon, HTMLStencilElement {
    }
    var HTMLFcIconElement: {
        prototype: HTMLFcIconElement;
        new (): HTMLFcIconElement;
    };
    interface HTMLFcIllustrationElement extends Components.FcIllustration, HTMLStencilElement {
    }
    var HTMLFcIllustrationElement: {
        prototype: HTMLFcIllustrationElement;
        new (): HTMLFcIllustrationElement;
    };
    interface HTMLFcImageElement extends Components.FcImage, HTMLStencilElement {
    }
    var HTMLFcImageElement: {
        prototype: HTMLFcImageElement;
        new (): HTMLFcImageElement;
    };
    interface HTMLElementTagNameMap {
        "fc-icon": HTMLFcIconElement;
        "fc-illustration": HTMLFcIllustrationElement;
        "fc-image": HTMLFcImageElement;
    }
}
declare namespace LocalJSX {
    interface FcIcon {
        "color"?: string;
        "group"?: string;
        "name"?: string;
        "size"?: string;
    }
    interface FcIllustration {
        "name"?: string;
        "size"?: string;
    }
    interface FcImage {
        "height"?: number;
        "name"?: string;
        "styles"?: object;
        "width"?: number;
    }
    interface IntrinsicElements {
        "fc-icon": FcIcon;
        "fc-illustration": FcIllustration;
        "fc-image": FcImage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fc-icon": LocalJSX.FcIcon & JSXBase.HTMLAttributes<HTMLFcIconElement>;
            "fc-illustration": LocalJSX.FcIllustration & JSXBase.HTMLAttributes<HTMLFcIllustrationElement>;
            "fc-image": LocalJSX.FcImage & JSXBase.HTMLAttributes<HTMLFcImageElement>;
        }
    }
}
